# Generated by Django 5.0.6 on 2024-07-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zaiavka_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
        migrations.AddField(
            model_name='grade',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
            preserve_default=False,
        ),
    ]
